#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Update opord/README.md with tiered PDF links."""
from pathlib import Path

README = Path(__file__).resolve().parents[1] / "README.md"

parts = [
    "# Operatsioon \u201ePeegel\u201c \u2014 OPORD\n\n",
    "Eesti keeles koostatud viiepunktiline **paranemis-teekond** (OPORD-formaat) vastutegevuseks ps\u00fchholoogilisele m\u00f5jutamisele.\n\n",
    "> *Paranemine algab sellel hetkel, kui sa m\u00f5istad, et sa pole katki olnudki.*\n\n",
    "> *Kohtleme k\u00f5iki asjaosalisi nagu terveid, t\u00e4iesti normaalseid inimesi.*\n\n",
    "> *Kui inimesel on roll, eesm\u00e4rk ja konkreetsed juhised \u2014 ta tihti teebki seda.*\n\n",
    "## Allalaadimine\n\n",
    "### Esimene kontakt (K0 \u2014 soovitatav)\n\n",
    "| Formaat | Link |\n",
    "|---------|------|\n",
    "| **PEEGEL TUUM (PDF)** | [PEEGEL_TUUM.pdf](PEEGEL_TUUM.pdf) |\n",
    "| **PEEGEL TUUM (Markdown)** | [PEEGEL_TUUM.md](PEEGEL_TUUM.md) |\n",
    "| **Sidepakkide ZIP** | [Operatsioon-Peegel-sidepakkid.zip](Operatsioon-Peegel-sidepakkid.zip) |\n\n",
    "### Lugejateed (K1)\n\n",
    "| Tee | PDF |\n",
    "|-----|-----|\n",
    "| A \u2014 Isa kriisis | [PEEGEL_TEE_A.pdf](PEEGEL_TEE_A.pdf) |\n",
    "| B \u2014 Skeptik | [PEEGEL_TEE_B.pdf](PEEGEL_TEE_B.pdf) |\n",
    "| C \u2014 Pere | [PEEGEL_TEE_C.pdf](PEEGEL_TEE_C.pdf) |\n",
    "| D \u2014 Demomees | [PEEGEL_TEE_D.pdf](PEEGEL_TEE_D.pdf) |\n",
    "| E \u2014 Venekeelne | [PEEGEL_RU_KIHT0.pdf](PEEGEL_RU_KIHT0.pdf) |\n",
    "| F \u2014 Juht | [PEEGEL_TEE_F.pdf](PEEGEL_TEE_F.pdf) |\n\n",
    "Skeem: [Lisa AQ](lisad/lisa-aq-sidepakkide-jaotus-skeem.md)\n\n",
    "### T\u00e4ielik pakett (K2)\n\n",
    "| Formaat | Link |\n",
    "|---------|------|\n",
    "| **DOCX** | [OPERATSIOON_PEEGEL_KOOS_LISADEGA.docx](OPERATSIOON_PEEGEL_KOOS_LISADEGA.docx) |\n",
    "| **ZIP \u2014 kogu pakett** | [Operatsioon-Peegel-kogu-pakett.zip](Operatsioon-Peegel-kogu-pakett.zip) |\n",
    "| **PDF (t\u00e4ielik OPORD)** | [OPERATSIOON_PEEGEL_OPORD.pdf](OPERATSIOON_PEEGEL_OPORD.pdf) |\n",
    "| **Markdown** | [OPERATSIOON_PEEGEL_OPORD.md](OPERATSIOON_PEEGEL_OPORD.md) |\n",
    "| **Pull request** | [PR #1](https://github.com/reneealuste-commits/Unpluged-Al/pull/1) |\n\n",
    "### Prinditavad t\u00f6\u00f6riistad\n\n",
    "| T\u00f6\u00f6riist | Link |\n",
    "|----------|------|\n",
    "| Taskukaardid | [TASKUKAARDID_PRINT.pdf](TASKUKAARDID_PRINT.pdf) \u00b7 [rahakott](TASKUKAARDID_RAHAKOTT.pdf) |\n",
    "| Lendleht | [LENDLEHT_PRINT.pdf](LENDLEHT_PRINT.pdf) |\n",
    "| Toidu uurimust\u00f6\u00f6 | [TOITUMINE_UURIMUSTOO.pdf](TOITUMINE_UURIMUSTOO.pdf) |\n\n",
    "## PDF uuendamine\n\n",
    "```bash\n",
    "cd opord\n",
    "python3 generate_pdf.py          # K0, teed A\u2013F + t\u00e4ielik OPORD\n",
    "python3 generate_packages.py     # sidepakkide ZIP\n",
    "python3 generate_toidu_pdf.py\n",
    "python3 generate_taskukaardid_pdf.py\n",
    "```\n\n",
    "## Kihtide arhitektuur (Lisa AQ)\n\n",
    "| Kiht | Mis see on |\n",
    "|------|------------|\n",
    "| **K0** | PEEGEL_TUUM \u2014 esimene kontakt |\n",
    "| **K1** | Tee PDF-id A\u2013F |\n",
    "| **K2** | T\u00e4ielik OPERATSIOON_PEEGEL_OPORD.pdf |\n",
    "| **K3** | Spetsialist (Lisa T, AL, AA jne) \u2014 n\u00f5udmisel |\n\n",
    "Auditi skoor: **7,8/10** (Lisa AP). Valmis piiratud levituseks demomeestele.\n\n",
    "## Struktuur\n\n",
    "Dokument j\u00e4rgib Maakaitse k\u00e4siraamatu viiepunktilist OPORD-formaati:\n\n",
    "1. Olukord\n",
    "2. P\u00f5hi\u00fclesanne\n",
    "3. T\u00e4ideviimine\n",
    "4. Lahinguteenindus\n",
    "5. Juhtimine ja side\n\n",
    "Lisa A\u2013AQ: Tugeva Isa seeria, lisad, SWOT, sidepakkide skeem.\n",
]

README.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {README}")
