#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate Lisa AP with updated audit scores after tiered packages."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "lisad" / "lisa-ap-swot-ja-lugeja-audit.md"

parts = [
    "# Lisa AP \u2014 SWOT ja lugeja-audit (lugejale orienteeritud)\n\n",
    "**P\u00f5him\u00f5te:** Iga dokument peab vastama k\u00fcsimusele: **mida LUGEJA saab \u2014 mitte mida autor teab.**  \n",
    "**Eesm\u00e4rk:** Aus enesehinnang enne levitamist; t\u00e4iendused p\u00f5hinevad lugeja kogemusel  \n",
    "**Seotud:** Lisa P, Lisa M (LIHTSUS), Lisa AD (lood), Lisa AM, Lisa AN, Lisa AO, **Lisa AQ**\n\n",
    "> **Lugeja saab:** ausa enesehinnangu \u2014 kas materjal on valmis levitamiseks.  \n",
    "> **Loe seda kui:** tahad n\u00e4ha SWOT-i ja auditi skoori.  \n",
    "> **\u00c4ra loe kui:** otsid praktilist igap\u00e4evategu \u2014 alusta PEEGEL_TUUM.pdf.\n\n",
    "---\n\n",
    "## 1. Lugejale orienteeritud p\u00f5him\u00f5te (meie kompass)\n\n",
    "| Autori k\u00f5lb | Lugeja k\u00f5lb |\n",
    "|-------------|--------------|\n",
    "| \u201eMeil on plaan\u201c | \u201eMida **mina** t\u00e4na teen?\u201c |\n",
    "| \u201eLoe k\u00f5ik 40 lisa\u201c | \u201eAlusta **\u00fchest** kohast oma olukorra jaoks\u201c |\n",
    "| \u201eUsu mind\u201c | \u201e**\u00c4ra usu** \u2014 uuri, kaalu, vali ise\u201c (OPORD avaleht) |\n",
    "| Tabelid ja KPI | **Lugu** + **\u00fcks tegu** (Lisa AD) |\n",
    "| Trauma ignoreerimine | **Turvalisus enne loogikat** (Lisa P) |\n\n",
    "**Test:** Kas 12-aastane (Lisa M reegel) saab \u00fchest l\u00f5igust aru, mida teha?\n\n",
    "---\n\n",
    "## 2. SWOT \u2014 Operatsioon \u201ePeegel\u201c (lugeja perspektiiv)\n\n",
    "### S \u2014 Tugevused (mida lugeja saab)\n\n",
    "| Tugevus | Lugeja kasu | Lisa |\n",
    "|---------|-------------|------|\n",
    "| **Paranemis-teekond**, mitte k\u00e4sk | Ei triggerda militaarkaitsepositsiooni | OPORD, Lisa P |\n",
    "| **Kihtide arhitektuur K0\u2013K3** | Ei pea k\u00f5ike korraga | Lisa AQ, PEEGEL_TUUM |\n",
    "| **Trauma-teadlik suhtlus** | Turvaline vestlus peres | Lisa P, S, H |\n",
    "| **Praktilised checklistid** | \u00dcks tegu t\u00e4na | Lisa N, AD, X, AO |\n",
    "| **Lood, mitte ainult teooria** | Inimene m\u00f5istab loo kaudu | Lisa AD, AI |\n",
    "| **Kriitiline m\u00f5tlemine kutsutud** | Lugeja s\u00f5ltumatus | OPORD p\u00f5him\u00f5te |\n",
    "| **Steiger / inimesekeskne juhtimine** | T\u00f5estatud raamistik | Lisa I |\n",
    "| **Realistlik raamat/plaan** | Usaldusv\u00e4\u00e4rne maht | Lisa AM |\n",
    "| **Venekeelne rada eraldi** | ~300k ei j\u00e4\u00e4 ilma | Lisa AN |\n",
    "| **Demomehe orgaaniline mudel** | Ei tundu massreklaam | Lisa N, AJ |\n",
    "| **Lugeja-sildid** | \u201eLoe seda kui\u2026\u201c igal pealisel | Lisa AQ \u00a73 |\n\n",
    "### W \u2014 N\u00f5rkused (mida lugeja kogeb)\n\n",
    "| N\u00f5rkus | Lugeja risk | Parandus |\n",
    "|--------|-------------|----------|\n",
    "| **K2 endiselt suur** | Dropout kui annad liiga palju | K0 vaikimisi (Lisa AQ) |\n",
    "| **Segateemad K2-s** | \u201eMis see \u00fcldse on?\u201c | Kihtide jaotus |\n",
    "| **Autori usaldus** | \u201eKes see on?\u201c | Lisa R + t\u00f6\u00f6 tulemustega |\n",
    "| **RU tekst vajab kinnitust** | Pool auditooriumit v\u00e4ljas | Kiht 0 RU + Mihhail |\n",
    "| **Steiger \u00f5igused lahtised** | \u201eKas legaalne?\u201c | Lisa AM Huber |\n",
    "| **Intiimsuse osa tabu** | Trigger | Lisa AA silt |\n\n",
    "### O \u2014 V\u00f5imalused\n\n",
    "| V\u00f5imalus | Lugeja kasu |\n",
    "|----------|-------------|\n",
    "| Steigeri uustr\u00fckk 2\u201310k | K\u00e4ep\u00e4rane raamat |\n",
    "| M. U\u0161akov RU peer-educator | Usaldus vene kogukonnas |\n",
    "| Sidepakkide ZIP | \u00dcks klikk \u00f5ige paketiga | Lisa AQ |\n",
    "| Peegel taskuraamat | Ilma litsentsita kohe | Lisa AK |\n",
    "| Ultimate Power filter | Sportlane/ettev\u00f5tja keel | Lisa AO |\n\n",
    "### T \u2014 Ohud\n\n",
    "| Oht | Kaitse |\n",
    "|-----|--------|\n",
    "| \u201ePropaganda\u201c | \u00c4ra usu, uuri (OPORD) |\n",
    "| Trauma trigger | Lisa P; Lisa AJ kuldne tee |\n",
    "| Heli / RU konflikt | Eraldi kanalid (Lisa AN) |\n",
    "| Lugeja burnout | LIHTSUS: \u00fcks tegu |\n",
    "| OPSEC | Lisa AJ kontrollitud levitus |\n\n",
    "---\n\n",
    "## 3. SWOT \u2192 tegevus\n\n",
    "| # | Tegevus | Vastutaja | Staatus |\n",
    "|---|---------|-----------|--------|\n",
    "| 1 | Lugejateed OPORD-i | Renee | Tehtud |\n",
    "| 2 | Kiht 0 RU 1 lk | Mihhail/Renee | Mustand valmis |\n",
    "| 3 | Sidepakkide skeem + ZIP | Skript | **Tehtud** (Lisa AQ) |\n",
    "| 4 | PEEGEL_TUUM + tee PDF-id | Skript | **Tehtud** |\n",
    "| 5 | Lugeja-sildid peamistele lisadele | Skript | **Tehtud** |\n",
    "| 6 | 100 demomehe pilot P0 | Renee | Lisa N |\n",
    "| 7 | Huber p\u00e4ring | Heli | Ootel |\n\n",
    "---\n\n",
    "## 4. Lugejateed (vali \u00fcks)\n\n",
    "| Tee | Kellele | PDF |\n",
    "|-----|---------|-----|\n",
    "| **A** Isa kriisis | Isa, peres kriis | `PEEGEL_TEE_A.pdf` |\n",
    "| **B** Skeptik | Ei usu kohe | `PEEGEL_TEE_B.pdf` |\n",
    "| **C** Pere | Tugevdada kodu | `PEEGEL_TEE_C.pdf` |\n",
    "| **D** Demomees | SOK / Aluste_kool | `PEEGEL_TEE_D.pdf` |\n",
    "| **E** Venekeelne | RU kodanik | `PEEGEL_RU_KIHT0.pdf` |\n",
    "| **F** Juht | Koolitus, KV | `PEEGEL_TEE_F.pdf` |\n\n",
    "Esimene kontakt alati: **`PEEGEL_TUUM.pdf`** (K0). Skeem: **Lisa AQ**.\n\n",
    "---\n\n",
    "## 5. Lugeja-audit (10 punkti)\n\n",
    "| # | K\u00fcsimus |\n",
    "|---|--------|\n",
    "| 1 | Kas esimene l\u00f5ik \u00fctleb **mida lugeja saab**? |\n",
    "| 2 | Kas on **\u00fcks konkreetne tegu**? |\n",
    "| 3 | Kas 12-aastane saab tuuma aru? |\n",
    "| 4 | Kas trauma-teadlik (Lisa P)? |\n",
    "| 5 | Kas on \u201eloe seda, kui\u2026\u201c silt? |\n",
    "| 6 | Kas lugeja saab lahkuda ilma surve tundmata? |\n",
    "| 7 | Kas on viide edasi, mitte k\u00f5ik korraga? |\n",
    "| 8 | Kas numbrid realistlikud (Lisa AM)? |\n",
    "| 9 | Kas RU/ET m\u00f5eldud (Lisa AN)? |\n",
    "| 10 | Kas kutsub uurima, mitte uskuma? |\n\n",
    "**Skoor:** 8\u201310 jah \u2192 levita. 5\u20137 \u2192 t\u00e4ienda. <5 \u2192 kirjuta uuesti.\n\n",
    "---\n\n",
    "## 6. Auditi tulemus (2026-07-24, p\u00e4rast kihtide jaotust)\n\n",
    "| Valdkond | Enne | P\u00e4rast |\n",
    "|----------|------|--------|\n",
    "| Kriitiline m\u00f5tlemine | 9/10 | 9/10 |\n",
    "| Trauma-teadlikkus | 8/10 | 8/10 |\n",
    "| Lihtsus / lugejateed | 6/10 | **8/10** |\n",
    "| Maht / fookus | 5/10 | **8/10** |\n",
    "| Usaldus / OPSEC | 7/10 | 7/10 |\n",
    "| Venekeelne | 5/10 | **6/10** (mustand) |\n",
    "| Praktilised t\u00f6\u00f6riistad | 9/10 | 9/10 |\n\n",
    "**Kokku: 6,9/10 \u2192 7,8/10** \u2014 valmis **piiratud levituseks** demomeestele (P0-TUUM + tee PDF). Mass enne 100 demomehe tagasisidet.\n\n",
    "---\n\n",
    "## 7. J\u00e4rgmised ettepanekud\n\n",
    "1. Kiht 0 RU tr\u00fckk (kinnita emakeelek\u00f5nele)  \n",
    "2. 100 demomehe pilot P0-TUUM  \n",
    "3. Heli kinnitus RU kanal  \n",
    "4. Huber vastus enne Steigeri RU tekstis  \n",
    "5. Tagasiside 30 p\u00e4eva p\u00e4rast \u2014 uuenda audit\n\n",
    "---\n\n",
    "*Lisa AP \u2014 Operatsioon \u201ePeegel\u201c. SWOT ja audit lugeja kesksest p\u00f5him\u00f5ttest. 2026-07-24.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
