#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Lisa AT - LIHTSUS and kui kinni jaid decision tree."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "lisad" / "lisa-at-lihtsus-kui-kinni-jaid.md"

parts = [
    "# Lisa AT \u2014 LIHTSUS: kui kinni j\u00e4id\n\n",
    "> **Lugeja saab:** \u00fche otsuspuu \u2014 mida teha, kui ei tea edasi minna.  \n",
    "> **Loe seda kui:** oled \u00fclekoormatud, segaduses v\u00f5i ei tea j\u00e4rgmist sammu.  \n",
    "> **\u00c4ra loe kui:** tead juba oma tee (A\u2013F) \u2014 ava vastav PDF ja j\u00e4rgi seda.\n\n",
    "**Operatsioon \u201ePeegel\u201c** | Lihtsuse printsiip kogu materjali l\u00e4biv reegel  \n",
    "**Seotud:** Lisa M (LIHTSUS), Lisa AP (audit), Lisa AQ (kihtid), PEEGEL_TUUM (K0)\n\n",
    "---\n\n",
    "## P\u00f5hireegel\n\n",
    "> *\u201e**Kui meeskond ei tea plaani, siis nad ei saa ju seda t\u00e4ita!**\u201c*\n\n",
    "Iga dokument, iga demomees, iga lugeja peab teadma **\u00fcks j\u00e4rgmine samm** \u2014 mitte kogu raamatukogu korraga.\n\n",
    "| LIHTSUS kodanikule | LIHTSUS v\u00f5rgustikule |\n",
    "|--------------------|----------------------|\n",
    "1. **\u00dcks plaan** \u2014 mida t\u00e4na teen | 1. Iga s\u00f5num arusaadav 12-aastasele |\n",
    "2. **\u00dcks t\u00f5de korraga** | 2. Iga \u00fcksus teab oma \u00fchesande (Lisa K) |\n",
    "3. **\u00dcks peegel** \u2014 enne ekraani | 3. Automatiseeri alles kui plaan selge (Lisa L) |\n\n",
    "**Test (Lisa AP):** Kas 12-aastane saab \u00fchest l\u00f5igust aru, **mida teha**?\n\n",
    "---\n\n",
    "## Universaalne otsuspuu \u2014 alusta siit\n\n",
    "Loe **\u00fcks rida** \u2014 tee see. \u00c4ra loe tabelit l\u00f5puni.\n\n",
    "| # | Kui sa tunned seda | Tee kohe (ainult see) |\n",
    "|---|-------------------|------------------------|\n",
    "1 | **Oht elule, enesetapp, v\u00e4givald** | Helista **112** v\u00f5i Eluliin **655 8088** \u00b7 Lisa **H** |\n",
    "2 | **Esimene kord Peegliga** | Ava **PEEGEL_TUUM.pdf** (K0) \u00b7 vali \u00fcks tee A\u2013F |\n",
    "3 | **Liiga palju infot, upud** | Sulge OPORD \u00b7 j\u00e4ta ainult K0 v\u00f5i oma tee PDF \u00b7 **\u00fcks tegu t\u00e4na** (TUUM) |\n",
    "4 | **Ei tea, milline tee** | Vt allpool **Tee valik** \u00b7 v\u00f5i SMS **56980062**, s\u00f5na **Peegel** |\n",
    "5 | **Tahan aidata kedagi teist** | Lisa **Q** \u00a74 (kata ja liigu) \u00b7 Lisa **P** \u00b7 \u00e4ra oota palvet |\n",
    "6 | **Olen demomees / SOK** | Lisa **N** checklist \u00b7 siis **Q** (GOTWA) \u00b7 siis **AD** (\u00fcks lugu) |\n",
    "7 | **Juht / koolitus** | Lisa **I** \u00b7 siis **P** \u00b7 siis **L** |\n",
    "8 | **Venekeelne** | **PEEGEL_RU_KIHT0.pdf** \u00b7 Lisa **AN** |\n",
    "9 | **Saadan materjali edasi** | Lisa **AQ** \u00b7 alusta **P0-TUUM** \u00b7 \u00fcks pakett korraga |\n",
    "10 | **Tahan k\u00f5ike (K2)** | K\u00fcsi lugemiskinnitust (Lisa **AJ**) \u00b7 siis OPORD PDF |\n\n",
    "---\n\n",
    "## Tee valik (K1) \u2014 \u00fcks rida\n\n",
    "| Tee | Kellele | Ava kohe | J\u00e4rgmine samm p\u00e4rast PDF-i |\n",
    "|-----|---------|----------|------------------------------|\n",
    "| **A** | Isa kriisis | `PEEGEL_TEE_A.pdf` | Lisa H \u2192 raamat F \u2192 Lisa P \u2192 Lisa AD |\n",
    "| **B** | Skeptik | `PEEGEL_TEE_B.pdf` | Lisa R \u2192 Lisa T (kokkuv\u00f5te) \u00b7 \u00e4ra usu \u2014 uuri |\n",
    "| **C** | Pere | `PEEGEL_TEE_C.pdf` | raamat A \u2192 D \u2192 E \u2192 Lisa M (manifest) |\n",
    "| **D** | Demomees | `PEEGEL_TEE_D.pdf` | Lisa N \u2192 I \u2192 Q \u2192 AO \u2192 Lisa X |\n",
    "| **E** | Venekeelne | `PEEGEL_RU_KIHT0.pdf` | Lisa AN \u00b7 RU kanal eraldi |\n",
    "| **F** | Juht / KV | `PEEGEL_TEE_F.pdf` | Lisa I \u2192 P \u2192 L |\n\n",
    "Skeem ja ZIP: **Lisa AQ**.\n\n",
    "---\n\n",
    "## Kihtide reegel (m\u00e4leta \u00fcks lause)\n\n",
    "> **K0 vaikimisi. K1 kui tee selge. K2 ainult kui k\u00fcsib. K3 ainult vajadusel.**\n\n",
    "| Kiht | Fail | Millal |\n",
    "|------|------|--------|\n",
    "| K0 | PEEGEL_TUUM.pdf | Alati esimene |\n",
    "| K1 | PEEGEL_TEE_*.pdf | Valitud tee |\n",
    "| K2 | OPERATSIOON_PEEGEL_OPORD.pdf | Soovija \u00abk\u00f5ik\u00bb |\n",
    "| K3 | Lisa T, AL, \u2026 | Partner / anal\u00fc\u00fctik |\n\n",
    "---\n\n",
    "## \u00dcks tegu t\u00e4na (kui ei suuda rohkem)\n\n",
    "Vali **\u00fcks** \u2014 mitte k\u00f5ik:\n\n",
    "1. **Hinga** \u2014 4 s sisse, 6 s v\u00e4lja, 3 korda\n",
    "2. **Kuula** \u2014 \u00fcks inimene ilma parandamiseta\n",
    "3. **Kirjuta** \u2014 *\u201eMa tunnen praegu ___\u201c*\n",
    "4. **Liigu** \u2014 10 min jalutusk\u00e4ik v\u00f5i 90 s rippumist\n",
    "5. **Loe** \u2014 \u00fcks lk oma tee PDF-ist\n",
    "6. **GOTWA** \u2014 \u00fcks minut perele enne v\u00e4ljumist (Lisa Q)\n",
    "7. **Peegel** \u2014 loe manifest \u00fcks kord (Lisa M)\n\n",
    "---\n\n",
    "## Rollide kiirplaan\n\n",
    "### Lugeja (kodanik)\n",
    "1. PEEGEL_TUUM \u2192 2. vali tee \u2192 3. \u00fcks tegu t\u00e4na \u2192 4. \u00e4ra ava K2 enne kui vaja\n\n",
    "### Demomees (Aluste_kool)\n",
    "1. Lisa N checklist \u2192 2. Lisa Q (GOTWA + kata ja liigu) \u2192 3. Lisa AD (\u00fcks lugu) \u2192 4. anna ainult P0 v\u00f5i P1\n\n",
    "### Abistaja (l\u00e4hedane, s\u00f5ber)\n",
    "1. Lisa H (kui kriis) \u2192 2. Lisa Q \u00a74 \u2192 3. Lisa P \u2192 4. \u00fcks konkreetne samm + ajaline lootus\n\n",
    "### Koordinaator / levitaja\n",
    "1. Lisa AQ pakett \u2192 2. Lisa AJ (OPSEC) \u2192 3. \u00fcks kanal korraga \u2192 4. tagasiside Lisa AP\n\n",
    "---\n\n",
    "## Lisa-p\u00f5hine \u00abkui kinni j\u00e4id\u00bb (peamised)\n\n",
    "| L\u00f5petasid / oled siin | J\u00e4rgmine samm |\n",
    "|----------------------|---------------|\n",
    "| **PEEGEL_TUUM** | Vali tee A\u2013F \u00b7 v\u00f5i \u00fcks tegu t\u00e4na |\n",
    "| **Lisa H** | raamat F (Murra ring) \u00b7 Lisa P \u00b7 numbrid k\u00e4es |\n",
    "| **Lisa P** | Lisa Q (suhtlus) v\u00f5i Lisa S (miks keha nii reageerib) |\n",
    "| **Lisa N** | Lisa Q igap\u00e4ev \u00b7 Lisa AD lugu \u00b7 Lisa X taskukaart |\n",
    "| **Lisa Q** | Lisa P (valideerimine) \u00b7 praktika homme uuesti |\n",
    "| **Lisa I** | Lisa P + Lisa L (riik) v\u00f5i Lisa N (demomees) |\n",
    "| **Lisa M** | \u00dcks manifest hommikul \u00b7 \u00fcks tegu p\u00e4eval \u00b7 korda 7 p\u00e4eva |\n",
    "| **Lisa AD** | Lisa X v\u00e4ljapoole \u00b7 Lisa N checklist \u00f5htul |\n",
    "| **Lisa AQ** | Genereeri ZIP \u00b7 anna P0 \u00b7 oota tagasisidet |\n",
    "| **OPORD (K2)** | Tagasi K0-sse \u00b7 vali \u00fcks lisa \u00b7 \u00e4ra loe l\u00f5puni korraga |\n\n",
    "---\n\n",
    "## Lihtsuse audit (2026-07-25)\n\n",
    "**\u00dclesanne:** Leia kohad, kus lugeja v\u00f5ib kinni j\u00e4\u00e4da ilma j\u00e4rgmise sammu juhist.\n\n",
    "### Leitud l\u00fcngad (enne parandust)\n\n",
    "| L\u00fcng | Risk | Parandus |\n",
    "|-----|------|----------|\n",
    "| LIHTSUS ainult Lisa M-s ja Faas V-s | P\u00f5him\u00f5te ei l\u00e4bi kogu paketti | Lisa AT + OPORD/TUUM plokk |\n",
    "| PEEGEL_TUUM ilma \u00abkinni j\u00e4id\u00bb puuta | Esimene kontakt \u2014 suurim dropout | Otsuspuu TUUM-i |\n",
    "| Lisa H, N, Q, I, AD ilma j\u00e4rgmine samm | L\u00f5petad \u2014 ei tea edasi | Iga\u00fcksile l\u00f5pp-plokk |\n",
    "| Lisa P E3 vastus \u00fcldine | Ei viita K0/AT-le | Viide Lisa AT |\n",
    "| Lisa AQ demomehele | Selge levitus, aga mitte lugejale | AT viide |\n",
    "| Lisa K (700+ rida) | Uppumine nimedes | \u00abSa ei pea kedagi tundma\u00bb + AT |\n\n",
    "### Parandused (selles versioonis)\n\n",
    "- Lisa **AT** (see dokument) \u2014 \u00fcks otsuspuu kogu paketile\n",
    "- **PEEGEL_TUUM** \u2014 LIHTSUS + kui kinni j\u00e4id\n",
    "- **OPORD** \u2014 lihtsuse printsiip lugejateede juures\n",
    "- **Lisa H, N, Q, P, I, M, AD, AQ** \u2014 \u00abJ\u00e4rgmine samm\u00bb plokk\n",
    "- **Lisa AP** \u2014 audit skoor uuendatud\n\n",
    "### Auditi skoor (lihtsus)\n\n",
    "| Valdkond | Enne (07-24) | P\u00e4rast (07-25) |\n",
    "|----------|--------------|----------------|\n",
    "| Lihtsus / lugejateed | 8/10 | **9/10** |\n",
    "| \u00abKui kinni j\u00e4id\u00bb katvus | 4/10 | **9/10** |\n",
    "| **Kokku (Lisa AP)** | 7,8/10 | **8,2/10** |\n\n",
    "---\n\n",
    "## Kokkuv\u00f5te\n\n",
    "Sa ei pea tundma kogu plaani. Sa pead tundma **\u00fcks j\u00e4rgmine samm**.\n\n",
    "> **Kui sa ei tea, mida teha \u2014 oled \u00f5iges kohas. Ava see lisa. Vali \u00fcks rida. Tee see.**\n\n",
    "---\n\n",
    "*Lisa AT \u2014 Operatsioon \u201ePeegel\u201c. Lihtsuse printsiip ja otsuspuu. 25. juuli 2026.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
