#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate PEEGEL_TUUM.md - K0 entry document."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "PEEGEL_TUUM.md"

parts = [
    "# PEEGEL TUUM \u2014 K0\n",
    "## Paranemis-teekond: esimene kontakt (~30 lk)\n\n",
    "**Klassifikatsioon:** Avalik \u2014 Eesti rahvale  \n",
    "**Kuup\u00e4ev:** 24. juuli 2026  \n",
    "**Koordinaator:** Renee Aluste  \n",
    "**T\u00e4ielik OPORD:** `OPERATSIOON_PEEGEL_OPORD.pdf` (ainult kui k\u00fcsid)\n\n",
    "> **Lugeja saab:** \u00fche selge sissejuhatuse ja \u00fche tee edasi \u2014 ilma 40 lisa \u00fclekoormuseta.  \n",
    "> **Loe seda kui:** see on sinu **esimene** kokkupuude Peegliga.  \n",
    "> **\u00c4ra loe kui:** oled kriisis \u2014 alusta kohe **Lisa H**-st (tee A).\n\n",
    "---\n\n",
    "## \U0001fa9e \u00c4ra usu mind\n\n",
    "See siin ei ole k\u00e4sk. See on kutse **kriitiliselt m\u00f5elda** \u2014 uurida, kaaluda, valida ise.\n\n",
    "| \u00c4ra tee seda | Tee seda |\n",
    "|--------------|----------|\n",
    "| Usu \u00fchte inimest | Loe allikaid, k\u00fcsi vastu |\n",
    "| J\u00e4rgi k\u00e4sku | Kaalu \u2014 iga keha on erinev |\n",
    "| V\u00f5ta vastu ilma uurimata | Uuri enne otsust |\n",
    "| L\u00f5peta elu surve all | **Naudi seda, mis on veel v\u00f5imalik** |\n\n",
    "> *\u201e**Paranemine algab sellel hetkel, kui sa m\u00f5istad, et sa pole katki olnudki.**\u201c \u2014 Renee Aluste*\n\n",
    "> *\u201e**Kohtleme k\u00f5iki asjaosalisi nagu terveid, t\u00e4iesti normaalseid inimesi.**\u201c*\n\n",
    "---\n\n",
    "## Vali \u00fcks tee (K1)\n\n",
    "Sa ei pea lugema k\u00f5ike. Vali **\u00fcks** rada:\n\n",
    "| Tee | Kellele | J\u00e4rgmine PDF |\n",
    "|-----|---------|-------------|\n",
    "| **A** | Isa kriisis | `PEEGEL_TEE_A.pdf` |\n",
    "| **B** | Skeptik | `PEEGEL_TEE_B.pdf` |\n",
    "| **C** | Pere | `PEEGEL_TEE_C.pdf` |\n",
    "| **D** | Demomees | `PEEGEL_TEE_D.pdf` |\n",
    "| **E** | Venekeelne | `PEEGEL_RU_KIHT0.pdf` |\n",
    "| **F** | Juht / koolitus | `PEEGEL_TEE_F.pdf` |\n\n",
    "Skeem: **Lisa AQ** (`lisa-aq-sidepakkide-jaotus-skeem.md`)\n\n",
    "---\n\n",
    "## KRIITILINE REEGEL \u2014 loe enne vestlust (Lisa P tuum)\n\n",
    "Traumatiseeritud inimesel on **teistsugune reaalsus**. Sa ei saa temaga tavaliselt koost\u00f6\u00f6d teha.\n\n",
    "| Tee | \u00c4ra tee |\n",
    "|-----|--------|\n",
    "| **Anna ruumi** ja turvalisus | \u00c4ra vaidle trauma olekus |\n",
    "| **Ignoreeri haukumist** | \u00c4ra feedi drama ega provokatsiooni |\n",
    "| **Tasusta rahulikku** | \u00c4ra anna halvale k\u00e4itumisele t\u00e4helepanu |\n\n",
    "**Kriisis kohe:** Eluliin **655 8088** \u00b7 Kriisiabi **116 123** \u00b7 Ohvriabi **116 006**\n\n",
    "T\u00e4ielik juhend: Lisa P (tee A v\u00f5i P2-TAIS)\n\n",
    "---\n\n",
    "## \u00dcks tegu t\u00e4na\n\n",
    "Vali **\u00fcks** \u2014 mitte k\u00f5ik:\n\n",
    "1. **Hinga** \u2014 4 sek sisse, 6 sek v\u00e4lja, 3 korda\n",
    "2. **Kuula** \u2014 \u00fcks inimene t\u00e4na ilma parandamiseta\n",
    "3. **Kirjuta** \u2014 \u00fcks lause: *\u201eMa tunnen praegu ___\u201c* (spordikommentaator)\n",
    "4. **Liigu** \u2014 10 min jalutusk\u00e4ik v\u00f5i 90 sek rippumist\n",
    "5. **Loe** \u2014 vali \u00fcks tee \u00fclevalt ja ava vastav PDF\n\n",
    "---\n\n",
    "## Mida see teekond pakub (l\u00fchidalt)\n\n",
    "Operatsioon \u201ePeegel\u201c on **paranemis-teekond** vastutegevuseks ps\u00fchholoogilisele m\u00f5jutamisele.\n",
    "See ei s\u00fcndi teooriast \u2014 see s\u00fcndis sellest, et **tulemused r\u00e4\u00e4givad iseenda eest**.\n\n",
    "| Valdkond | Mida saad |\n",
    "|----------|----------|\n",
    "| Trauma-teadlikkus | Turvaline vestlus peres (Lisa P, S, H) |\n",
    "| Keha ja uni | Walker, toit, liikumine (Lisa V, U, AB) |\n",
    "| Pere ja isa | Tugeva Isa seeria A\u2013G |\n",
    "| Suhtlus | GOTWA, h\u00e4\u00e4l, austav keel (Lisa Q) |\n",
    "| Kriitiline m\u00f5tlemine | \u00c4ra usu \u2014 uuri (see dokument) |\n\n",
  "**T\u00e4ielik audit:** Lisa AP \u2014 skoor 7,8/10 p\u00e4rast kihtide jaotust.\n\n",
    "---\n\n",
    "## Kihtide kord (m\u00e4leta)\n\n",
    "| Kiht | Mis see on |\n",
    "|------|------------|\n",
    "| **K0** | See dokument \u2014 TUUM |\n",
    "| **K1** | Sinu tee (A\u2013F) |\n",
    "| **K2** | T\u00e4ielik OPORD \u2014 kui k\u00fcsid |\n",
    "| **K3** | Spetsialist \u2014 ainult vajadusel |\n\n",
    "---\n\n",
    "## Kontakt ja edasi\n\n",
    "- **Demomees:** \u00fcksus Aluste_kool (Lisa N)\n",
    "- **Sidepakkide skeem:** Lisa AQ\n",
    "- **T\u00e4ielik pakett:** `Operatsioon-Peegel-sidepakkid.zip`\n",
    "- **Pull request:** github.com/reneealuste-commits/Unpluged-Al/pull/1\n\n",
    "---\n\n",
    "*PEEGEL TUUM \u2014 K0. Operatsioon \u201ePeegel\u201c. 24. juuli 2026. Renee Aluste.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
