#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Lisa AR - Vooglaid ja Paal demonstraatorid."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "lisad" / "lisa-ar-vooglaid-ja-paal-demonstraatorid.md"

parts = [
    "# Lisa AR \u2014 \u00dclo Vooglaid ja Indrek Paal (v\u00f5tmetegijad, demonstraatorid)\n\n",
    "> **Lugeja saab:** kodaniku-m\u00f5tleja eeskuju ja praktilise levitaja rolli.  \n",
    "> **Loe seda kui:** tahad aru saada, kes on Vooglaid ja miks ta sobib Peegli tuuma.  \n",
    "> **\u00c4ra loe kui:** otsid kiiret kriisiabi \u2014 alusta Lisa H.\n\n",
    "**Seotud:** Lisa M (kodaniku identiteet), Lisa Q (demonstraatorid), Lisa K, PEEGEL_TEE_B  \n",
    "**Kuup\u00e4ev:** 25. juuli 2026\n\n",
    "---\n\n",
    "## 1. Miks nad on siin\n\n",
    "Operatsioon \u201ePeegel\u201c kutsub: **\u00e4ra usu mind \u2014 uuri, kaalu, vali ise.** See ei ole uus idee Eestis.\n\n",
    "**\u00dclo Vooglaid** on seda \u00f5petanud aastak\u00fcmmendeid \u2014 *elanikust kodanikuks*, isem\u00f5tlejaks, mitte tarbijaks.\n",
    "**Indrek Paal** hoiab seda praktikas elus \u2014 kirjastus, sihtasutus, igap\u00e4evane kodaniku t\u00f6\u00f6.\n\n",
    "M\u00f5lemad on **demonstraatorid** (Lisa Q \u00a74): nad **n\u00e4itavad eeskuju**, mitte ei m\u00fc\u00fc massreklaamiga.\n\n",
    "---\n\n",
    "## 2. \u00dclo Vooglaid \u2014 kes ta on\n\n",
    "| | |\n|---|---|\n",
    "| **S\u00fcnniaeg** | 29. august 1935, Tallinn |\n",
    "| **Elukoht** | Raplamaa, Kohila vald |\n",
    "| **Amet** | Emeriitprofessor, sotsiaalteadlane, \u00fchiskonnategelane |\n",
    "| **Taust** | Tartu \u00fclikooli sotsioloogialabor; taasiseseisvumise \u00fclesehitus; Riigikogu (1992\u20132004); Rahvusraamatukogu n\u00f5ukogu esimees; ANDRAS asutaja |\n",
    "| **Kontakt** | ylo@vooglaid.org \u00b7 [vooglaid.org](https://vooglaid.org) |\n",
    "| **Sihtasutus** | Sihtasutus \u00dclo Vooglaiu m\u00f5ttep\u00e4rand (reg 90014247) \u2014 sihtasutus@vooglaid.org |\n\n",
    "### P\u00f5hiidee\n\n",
    "> *Inimene ei ole riigi tarbija. Inimene on **kodanik** \u2014 kes m\u00f5tleb, kaalub ja osaleb oma riigi hoidmisel.*\n\n",
    "See klapib Operatsioon \u201ePeegel\u201c tuumaga (Lisa M, OPORD avaleht).\n\n",
    "---\n\n",
    "## 3. \u00dclo Vooglaid \u2014 raamatud\n\n",
    "| Aasta | Pealkiri | Mida annab lugejale |\n",
    "|-------|----------|-------------------|\n",
    "| **2019** | **Elanikust kodanikuks. K\u00e4siraamat isem\u00f5tlejale** | **Peegli tee B tuum** \u2014 kodaniku m\u00f5tlemine, kriitiline pilk, \u00fchiskond |\n",
    "| 2019 | *Message to a Citizen* (inglise keeles) | Sama tuum rahvusvahelisele lugejale |\n",
    "| 2018 | **S\u00f5na on J\u00f5ud** | Raadio \u00d6\u00f6\u00fclikooli loengud 2001\u20132017 |\n",
    "| 2015 | **Aeg & Vaim** | M\u00f5tted, esseid, eluloolised fragmentid (koostaja Ivar Tr\u00f6ner) |\n",
    "| 2011 / **2025** | **Vanaisa** / **Vanaisa uued lood** | Lapsep\u00f5lv, eeskuju, perekond \u2014 90. s\u00fcnnip\u00e4evaks uus tr\u00fckk |\n",
    "| 1999 | Lastekodu kui kasvukeskkond | Haridus ja kasvatus (spetsialistidele) |\n",
    "| 1986 | Juhtimiss\u00fcsteemide morfoloogia ja dialektika | Juhtimisteooria (akadeemiline) |\n\n",
    "**Soovitus Peegli lugejale:** alusta **Elanikust kodanikuks** (ISBN 978-9949-88-952-5) \u2014 see on Vooglaidi tuum ja sobib **PEEGEL_TEE_B** skeptiku rajale.\n\n",
    "**Kolleegium** (*Elanikust kodanikuks*): Indrek Paal, Ivar Veskioja, Kaarel Talvoja, Margus Mikom\u00e4gi.\n\n",
    "---\n\n",
    "## 4. Indrek Paal \u2014 kes ta on\n\n",
    "| | |\n|---|---|\n",
    "| **Roll** | Ettev\u00f5tja, \u00dclo Vooglaiu m\u00f5ttep\u00e4randa praktiline hoidja |\n",
    "| **Ettev\u00f5tted** | Vana-Viru Kaubaveod O\u00dc (transport); \u00dclo Vooglaiu Kirjastus O\u00dc; Sihtasutus \u00dclo Vooglaiu m\u00f5ttep\u00e4rand; Expertus Trade O\u00dc |\n",
    "| **Taust** | 20+ aastat \u00e4ris; 1990ndate l\u00f5pul Muumi lasteajakirja vastutav v\u00e4ljaandja (Latrolle O\u00dc); \u00c4rip\u00e4eva arvamusartiklid (transport, riigi efektiivsus) |\n",
    "| **Kontakt** | Vana-Viru Kaubaveod: Vana-L\u00f5una 39/1, Tallinn \u00b7 tel 667 0111 \u00b7 sihtasutus@vooglaid.org (m\u00f5ttep\u00e4rand) |\n",
    "| **Seos Vooglaidiga** | Kirjastuse juhatuse liige; sihtasutuse juhatuse liige; *Elanikust kodanikuks* kolleegium |\n\n",
    "### P\u00f5hiidee\n\n",
    "> *M\u00f5ttep\u00e4rand ei ela riiulil. See elab inimestes, kes seda **praktikas** kannavad \u2014 tr\u00fck, transport, igap\u00e4evane t\u00f6\u00f6.*\n\n",
    "---\n\n",
    "## 5. Demonstraatorite roll (Lisa Q \u00a74 laiendus)\n\n",
    "Lisa Q m\u00e4\u00e4ratleb demonstraatorid (demomehed) Aluste_kooli kaudu. Vooglaid ja Paal on **v\u00f5tmetegijad-demonstraatorid** \u2014 teistsugune kanal, sama p\u00f5him\u00f5te.\n\n",
    "| Demonstraator | Mida ta n\u00e4itab | Mida ta ei tee |\n",
    "|---------------|----------------|---------------|\n",
    "| **\u00dclo Vooglaid** | 90-aastane kodaniku m\u00f5tleja; kriitiline pilk; perekonna ja eeskuju lood | Massreklaam; propaganda; \u00fchek\u00fclgne m\u00fc\u00fck |\n",
    "| **Indrek Paal** | Praktiline kodanik: transport, kirjastus, m\u00f5ttep\u00e4randa hoidmine | Poliitiline kampaania; sp\u00e4mm |\n\n",
    "### \u00dclo Vooglaid \u2014 operatsiooni roll\n\n",
    "- **Roll:** Kodaniku-m\u00f5tleja eeskuju; filosoofiline tuum enne OPORD-i\n",
    "- **Eesm\u00e4rk:** N\u00e4idata, et *elanikust kodanikuks* on Eestis juba ammu kirjas\n",
    "- **\u00dclesanded:**\n",
    "  1. Soovita lugejatel alustada **Elanikust kodanikuks** (tee B)\n",
    "  2. Anna isiklik tagasiside Reneele: kas Peegel ja Vooglaid klapivad\n",
    "  3. Jagada ainult vabatahtlikult \u2014 mitte surve all\n",
    "- **K\u00e4itumisjuhis:** Rahulik, kriitiline, emakeele rikkus. Trauma-teadlik (Lisa P) teiste suhtes.\n\n",
    "### Indrek Paal \u2014 operatsiooni roll\n\n",
    "- **Roll:** Praktiline demonstraator; m\u00f5ttep\u00e4randa ja tr\u00fcki levitaja\n",
    "- **Eesm\u00e4rk:** Tuua Vooglaidi tuum k\u00e4tte \u2014 raamat, seminar, isiklik vestlus\n",
    "- **\u00dclesanded:**\n",
    "  1. Levitada **Vanaisa uued lood** (2025) ja **Elanikust kodanikuks** sobivates ringkondades\n",
    "  2. Siduda sihtasutus ja Peegel ainult kui Vooglaid n\u00f5ustub\n",
    "  3. Anna tagasiside: mis formaat t\u00f6\u00f6tab (raamat vs PDF vs vestlus)\n",
    "  4. Transport/infrastruktuur teema \u2014 Lisa Z kontekstis (riigi efektiivsus)\n",
    "- **K\u00e4itumisjuhis:** Asjatundlik, praktiline. Lisa Q austav keel. Mitte masspostitus.\n\n",
    "---\n\n",
    "## 6. Lugejatee seos\n\n",
    "| Tee | Vooglaid / Paal |\n",
    "|-----|----------------|\n",
    "| **B Skeptik** | Alusta *Elanikust kodanikuks* \u2192 siis PEEGEL_TEE_B |\n",
    "| **C Pere** | *Vanaisa* / *Vanaisa uued lood* \u2014 eeskuju ja perekond |\n",
    "| **D Demomees** | Demonstraatori mudel: n\u00e4ita eeskuju, \u00e4ra m\u00fc\u00fc |\n",
    "| **F Juht** | Vooglaidi juhtimisteooria + Lisa I (Steiger) |\n\n",
    "---\n\n",
    "## 7. Sidepakk\n\n",
    "| Saaja | Pakett | Materjal |\n",
    "|-------|--------|----------|\n",
    "| Vooglaid | Isiklik vestlus | PEEGEL_TUUM + *Elanikust kodanikuks* v\u00f5rdlus |\n",
    "| Paal | E-kiri / kohtumine | P0-TUUM + kirjastuse koost\u00f6\u00f6v\u00f5imalus |\n\n",
    "**Oluline:** Enne avalikku sidumist \u2014 **Vooglaidi n\u00f5usolek**. Austus tema autonoomia vastu.\n\n",
    "---\n\n",
    "*Lisa AR \u2014 Operatsioon \u201ePeegel\u201c. Vooglaid ja Paal demonstraatorid. 2026-07-25.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
