#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate PEEGEL_TUUM.md - K0 entry document."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "PEEGEL_TUUM.md"

parts = [
    "# PEEGEL TUUM \u2014 K0\n",
    "## Paranemis-teekond: esimene kontakt (~30 lk)\n\n",
    "**Klassifikatsioon:** Avalik \u2014 Eesti rahvale  \n",
    "**Kuup\u00e4ev:** 24. juuli 2026  \n",
    "**Koordinaator:** Renee Aluste  \n",
    "**T\u00e4ielik OPORD:** `OPERATSIOON_PEEGEL_OPORD.pdf` (ainult kui k\u00fcsid)\n\n",
    "> **Lugeja saab:** \u00fche selge sissejuhatuse ja \u00fche tee edasi \u2014 ilma 40 lisa \u00fclekoormuseta.  \n",
    "> **Loe seda kui:** see on sinu **esimene** kokkupuude Peegliga.  \n",
    "> **\u00c4ra loe kui:** oled kriisis \u2014 alusta kohe **Lisa H**-st (tee A).\n\n",
    "---\n\n",
    "## \U0001fa9e \u00c4ra usu mind\n\n",
    "See siin ei ole k\u00e4sk. See on kutse **kriitiliselt m\u00f5elda** \u2014 uurida, kaaluda, valida ise.\n\n",
    "| \u00c4ra tee seda | Tee seda |\n",
    "|--------------|----------|\n",
    "| Usu \u00fchte inimest | Loe allikaid, k\u00fcsi vastu |\n",
    "| J\u00e4rgi k\u00e4sku | Kaalu \u2014 iga keha on erinev |\n",
    "| V\u00f5ta vastu ilma uurimata | Uuri enne otsust |\n",
    "| Usu oma esimest m\u00f5tet | **Usu keha** \u2014 keha ei valeta; aju v\u00f5ib (Lisa AW) |\n",
    "| L\u00f5peta elu surve all | **Naudi seda, mis on veel v\u00f5imalik** |\n\n",
    "> *\u201e**Paranemine algab sellel hetkel, kui sa m\u00f5istad, et sa pole katki olnudki.**\u201c \u2014 Renee Aluste*\n\n",
    "> *\u201e**Kohtleme k\u00f5iki asjaosalisi nagu terveid, t\u00e4iesti normaalseid inimesi.**\u201c*\n\n",
    "---\n\n",
    "## Esimene samm \u2014 \u00e4ra usu oma aju\n\n",
    "Enne kui loed edasi: **\u00e4ra usu automaatset m\u00f5tet.** Su aju on aastaid t\u00e4idetud algoritmide, v\u00f5\u00f5rkeelse sisu ja v\u00f5\u00f5raste narratiividega \u2014 see ei pruugi olla sinu h\u00e4\u00e4l.\n\n",
    "| \u00c4ra usu | Usu selle asemel |\n",
    "|---------|------------------|\n",
    "| Esimest m\u00f5tet (\u201ema tean\u201c, \u201eta m\u00f5tles\u201c) | **Keha signaali** \u2014 pingutus, hingamine, k\u00f5ht |\n",
    "| Tunnet, et \u201esee on fakt\u201c | K\u00fcsimust: *mis mul kehas toimub?* |\n",
    "| Voogu, mis triggerdab | Pausi \u2014 4 sek sisse, 6 sek v\u00e4lja |\n\n",
    "> *\u201e**Keha ei valeta. Aju v\u00f5ib** \u2014 eriti kui see on t\u00e4is v\u00f5\u00f5rast m\u00fcra.\u201c*\n\n",
    "T\u00e4ielik alus: **Lisa AW** (Kahneman + keha enne m\u00f5istust) \u00b7 **Lisa P** (turvalisus \u2192 keha \u2192 m\u00f5istus)\n\n",
    "---\n\n",
    "## Vali \u00fcks tee (K1)\n\n",
    "Sa ei pea lugema k\u00f5ike. Vali **\u00fcks** rada:\n\n",
    "| Tee | Kellele | J\u00e4rgmine PDF |\n",
    "|-----|---------|-------------|\n",
    "| **A** | Isa kriisis | `PEEGEL_TEE_A.pdf` |\n",
    "| **B** | Skeptik | `PEEGEL_TEE_B.pdf` |\n",
    "| **C** | Pere | `PEEGEL_TEE_C.pdf` |\n",
    "| **D** | Demomees | `PEEGEL_TEE_D.pdf` |\n",
    "| **E** | Venekeelne | `PEEGEL_RU_KIHT0.pdf` |\n",
    "| **F** | Juht / koolitus | `PEEGEL_TEE_F.pdf` |\n\n",
    "Skeem: **Lisa AQ** (`lisa-aq-sidepakkide-jaotus-skeem.md`)\n\n",
    "---\n\n",
    "## LIHTSUS \u2014 loe enne kui edasi l\u00e4hed\n\n",
    "> *\u201e**Kui meeskond ei tea plaani, siis nad ei saa ju seda t\u00e4ita!**\u201c*\n\n",
    "| Reegel | Mida see t\u00e4hendab |\n",
    "|--------|------------------|\n",
    "| **\u00dcks plaan** | Tea t\u00e4na \u00fcks asi \u2014 mitte kogu OPORD |\n",
    "| **\u00dcks tee** | A, B, C, D, E v\u00f5i F \u2014 mitte k\u00f5ik |\n",
    "| **\u00dcks tegu** | Allpool vali \u00fcks rida |\n",
    "| **K2 ainult kui k\u00fcsid** | T\u00e4ielik raamatukogu on vabatahtlik |\n\n",
    "T\u00e4ielik otsuspuu: **Lisa AT** (`lisa-at-lihtsus-kui-kinni-jaid.md`)\n\n",
    "---\n\n",
    "## KRIITILINE REEGEL \u2014 loe enne vestlust (Lisa P tuum)\n\n",
    "Traumatiseeritud inimesel on **teistsugune reaalsus**. Sa ei saa temaga tavaliselt koost\u00f6\u00f6d teha.\n\n",
    "| Tee | \u00c4ra tee |\n",
    "|-----|--------|\n",
    "| **Anna ruumi** ja turvalisus | \u00c4ra vaidle trauma olekus |\n",
    "| **Ignoreeri haukumist** | \u00c4ra feedi drama ega provokatsiooni |\n",
    "| **Tasusta rahulikku** | \u00c4ra anna halvale k\u00e4itumisele t\u00e4helepanu |\n\n",
    "**Kriisis kohe:** Eluliin **655 8088** \u00b7 Kriisiabi **116 123** \u00b7 Ohvriabi **116 006**\n\n",
    "T\u00e4ielik juhend: Lisa P (tee A v\u00f5i P2-TAIS)\n\n",
    "---\n\n",
    "## \u00dcks tegu t\u00e4na\n\n",
    "Vali **\u00fcks** \u2014 mitte k\u00f5ik:\n\n",
    "1. **Hinga** \u2014 4 sek sisse, 6 sek v\u00e4lja, 3 korda\n",
    "2. **Kuula** \u2014 \u00fcks inimene t\u00e4na ilma parandamiseta\n",
    "3. **Kirjuta** \u2014 \u00fcks lause: *\u201eMa tunnen praegu ___\u201c* (spordikommentaator)\n",
    "4. **Liigu** \u2014 10 min jalutusk\u00e4ik v\u00f5i 90 sek rippumist\n",
    "5. **Loe** \u2014 vali \u00fcks tee \u00fclevalt ja ava vastav PDF\n\n",
    "---\n\n",
    "## Mida see teekond pakub (l\u00fchidalt)\n\n",
    "Operatsioon \u201ePeegel\u201c on **paranemis-teekond** vastutegevuseks ps\u00fchholoogilisele m\u00f5jutamisele.\n",
    "See ei s\u00fcndi teooriast \u2014 see s\u00fcndis sellest, et **tulemused r\u00e4\u00e4givad iseenda eest**.\n\n",
    "| Valdkond | Mida saad |\n",
    "|----------|----------|\n",
    "| Trauma-teadlikkus | Turvaline vestlus peres (Lisa P, S, H) |\n",
    "| Keha ja uni | Walker, toit, liikumine (Lisa V, U, AB) |\n",
    "| Suur pilt | Kardashev, Musk s\u00fcsteem \u2014 hang on (Lisa AZ) |\n",
    "| Pere ja isa | Tugeva Isa seeria A\u2013G |\n",
    "| Suhtlus | GOTWA, h\u00e4\u00e4l, austav keel (Lisa Q) |\n",
    "| Kriitiline m\u00f5tlemine | \u00c4ra usu \u2014 uuri (see dokument) |\n",
    "| Aju vs keha | \u00c4ra usu oma aju \u2014 usu keha (Lisa AW) |\n\n",
  "**T\u00e4ielik audit:** Lisa AP \u2014 skoor **8,2/10** (Lisa AT lihtsuse audit, 25.07.2026).\n\n",
    "---\n\n",
    "## Kihtide kord (m\u00e4leta)\n\n",
    "| Kiht | Mis see on |\n",
    "|------|------------|\n",
    "| **K0** | See dokument \u2014 TUUM |\n",
    "| **K1** | Sinu tee (A\u2013F) |\n",
    "| **K2** | T\u00e4ielik OPORD \u2014 kui k\u00fcsid |\n",
    "| **K3** | Spetsialist \u2014 ainult vajadusel |\n\n",
    "**\u00dcks lause:** K0 vaikimisi \u00b7 K1 kui tee selge \u00b7 K2 kui k\u00fcsib \u00b7 K3 vajadusel.\n\n",
    "---\n\n",
    "## Kui kinni j\u00e4id \u2014 tee kohe \u00fcks neist\n\n",
    "| Olukord | J\u00e4rgmine samm |\n",
    "|---------|---------------|\n",
    "| Oht elule, enesetapp | **112** v\u00f5i **655 8088** \u00b7 Lisa H |\n",
    "| Liiga palju infot | Sulge see \u00b7 vali \u00fcks tee \u00b7 \u00fcks tegu t\u00e4na |\n",
    "| Ei tea milline tee | Lisa **AT** otsuspuu (10 rida) |\n",
    "| Tahan aidata teist | Lisa Q \u00a74 (kata ja liigu) + Lisa P |\n",
    "| Olen demomees | Lisa N checklist \u2192 Lisa Q |\n\n",
    "---\n\n",
    "## Kontakt ja edasi\n\n",
    "- **Demomees:** \u00fcksus Aluste_kool (Lisa N)\n",
    "- **Sidepakkide skeem:** Lisa AQ\n",
    "- **T\u00e4ielik pakett:** `Operatsioon-Peegel-sidepakkid.zip`\n",
    "- **Pull request:** github.com/reneealuste-commits/Unpluged-Al/pull/1\n\n",
    "---\n\n",
    "*PEEGEL TUUM \u2014 K0. Operatsioon \u201ePeegel\u201c. Uuendatud 25. juuli 2026 (LIHTSUS + Lisa AT). Renee Aluste.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
