#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "lisad" / "lisa-ao-ultimate-power-kokkuvote.md"

parts = [
    "# Lisa AO \u2014 Ultimate Power kokkuv\u00f5te (Peegli filter)\n\n",
    "**Allikas:** Lucio Buffalmano, *Ultimate Power* (The Power Moves, \u00a9 2018) \u2014 85 lk kokkuv\u00f5te enesearengu kirjandusest  \n",
    "**Eesm\u00e4rk:** T\u00f6\u00f6riistakasti lisa demomeestele; **mitte** OPORD tuum ega Steigeri asendus  \n",
    "**Seotud:** Lisa M (identiteet), Lisa I (inimesekeskne juhtimine), Lisa P (trauma), Lisa AN (RU demomees), Lisa AK\n\n",
    "> *See on destilleeritud \u00fclevaade. T\u00e4istekst on Buffalmano autorikaitse all \u2014 kasuta ideid, mitte kopeeri massiliselt.*\n\n",
    "---\n\n",
    "## 1. Mis see on\n\n",
    "| | |\n",
    "|---|---|\n",
    "| **Autor** | Lucio Buffalmano (*thepowermoves.com*) |\n",
    "| **Vorm** | 7 vaimse tuuma + muutuse teadus + enesekindlus + saavutamine + toitumine |\n",
    "| **Siht** | \u00dcksikisiku vaimne v\u00f5im \u2014 growth mindset, grit, confidence |\n",
    "| **Peegli roll** | **Lisa demomehele** (nt kickbox, ettev\u00f5tja) \u2014 3\u20135 ideed, mitte 85 lk |\n\n",
    "---\n\n",
    "## 2. Seitse tuumablokki \u2014 mis j\u00e4\u00e4b, mis filtreeritakse\n\n",
    "| # | Buffalmano | Peegli filter | Lisa |\n",
    "|---|------------|---------------|------|\n",
    "| 1 | **Sa saad muutuda** \u2014 aju on plastiline | \u2713 T\u00f5de. Alus k\u00f5igile. | Lisa M (Robbins), Lisa S |\n",
    "| 2 | **Growth mindset** (Dweck) | \u2713 \u00d5ppija enne tulemust. | Lisa I, Lisa M |\n",
    "| 3 | **Antifragile ego** (Taleb) | \u26a0\u0fe0f Kasulik, aga **mitte karmaks kestaks** | Lisa P: turvalisus enne loogikat |\n",
    "| 4 | **Locus of control** | \u2713 Vastutus \u2014 Extreme Ownership | Lisa M, OPORD |\n",
    "| 5 | **Passion / WHY** (Sinek) | \u2713 \u00dcks suund, mitte 100 projekti | Lisa M manifest |\n",
    "| 6 | **Outcome independence** | \u2713 Tee parim; tulemus ei defineeri sind | Lisa P, Steiger |\n",
    "| 7 | **Optimism / v\u00f5imalused** | \u2713 Ilma poliitilise \u00fclekuhutamiseta | Lisa T IPB ausus |\n\n",
    "---\n\n",
    "## 3. Mida v\u00f5tta demomehele (Kiht 0)\n\n",
    "### A. Grit (Duckworth)\n\n",
    "> *Passion + perseverance \u00fcle pika aja.*\n\n",
    "- Kickboxija, sportlane, ettev\u00f5tja \u2014 **sama keel**\n",
    "- \u00dcks tegu t\u00e4na > suur plaan homme\n",
    "- **Mitte:** \u201ev\u00f5ta kokku\u201c unetule inimesele (Lisa V)\n\n",
    "### B. Confidence kaudselt\n\n",
    "Buffalmano: enesekindlus **ei tule** \u201em\u00e4ngi enesekindlat\u201c. Tuleb:\n",
    "- growth mindset\n",
    "- selge WHY\n",
    "- midagi, milles oled hea (sport, pere, k\u00e4sit\u00f6\u00f6)\n\n",
    "**Peegel:** eeskuju enne s\u00f5na (Lisa N).\n\n",
    "### C. L\u00f5ika m\u00fcra\n\n",
    "- TV / sotsiaalmeedia \u00fclem\u00e4\u00e4rane v\u00f5rdlemine \u2192 OPORD \u201eAva silmad\u201c\n",
    "- **\u00dcks peegel p\u00e4evas** (Lisa M LIHTSUS)\n\n",
    "### D. Toitumine (l\u00fchidalt)\n\n",
    "- Terviktoit, v\u00e4hem suhkrut/t\u00f6\u00f6deldud\n",
    "- Lisa AE (\u00f5hk, liikumine) + toitumise uurimust\u00f6\u00f6\n",
    "- **Mitte** dieedidogma ega m\u00fc\u00fcgiloosung\n\n",
    "---\n\n",
    "## 4. Mida EI v\u00f5ta (v\u00f5i filtreeri Lisa P kaudu)\n\n",
    "| Risk | Miks | Peegli vastus |\n",
    "|------|------|---------------|\n",
    "| Antifragile ego \u2192 **k\u00f5va kest** | Trauma vajab turvalisust, mitte pannakse | Lisa P: kuula keha |\n",
    "| \u201eSa ei ole eriline\u201c \u2192 alav\u00e4\u00e4ristus | V\u00f5ib triggerdada | Lisa M: identiteet + t\u00f6\u00f6 teeb eriliseks |\n",
    "| The Power Moves \u00fcldine br\u00e4nd | Sotsiaald\u00fcnaamika / dominants | **Ainult see kokkuv\u00f5te** \u2014 mitte k\u00f5ik TPM artiklid |\n",
    "| \u00dcksikisiku kangelane | Peegel = pere + kogukond | Lisa E, Lisa K |\n",
    "| V\u00f5rdlus teistega | Infos\u00f5ja m\u00fcra | Lisa A (Unplugged) |\n\n",
    "---\n\n",
    "## 5. \u00dcks lause demomehele (ET / RU)\n\n",
    "**Eesti:**\n",
    "> Muutu iga p\u00e4ev natuke. \u00dcks tegu. \u00dcks aus peegel. Mitte ekraan.\n\n",
    "**Vene (mustand Mihhailile):**\n",
    "> Men\u00e4j\u00e4j ka\u017eddy den\u2019 nemnogo. Odno delo. Odin \u010destnyj vzglyad v zerkalo. Ne \u00e8kran.\n\n",
    "---\n\n",
    "## 6. Seosed teiste lisadega\n\n",
    "| Ultimate Power teema | Peegli lisa |\n",
    "|---------------------|-------------|\n",
    "| Growth mindset | Lisa I, Lisa M |\n",
    "| Grit / passion | Lisa AK (ohtlikkus sisemises dialoogis) |\n",
    "| Confidence | Lisa N demomees, Lisa AD lood |\n",
    "| L\u00f5ika sotsiaalmeedia | Raamat 01 Unplugged |\n",
    "| Toitumine | Lisa AE, toitumise uurimust\u00f6\u00f6 |\n",
    "| Trauma / turvalisus | **Lisa P alati peal** |\n",
    "| Venekeelne kanal | Lisa AN \u00a710 (M. U\u0161akov) |\n\n",
    "---\n\n",
    "## 7. Demomehe 5-punktiline checklist (Lisa AO)\n\n",
    "Kasuta 1\u00d7 n\u00e4dalas koos Lisa N checklistiga:\n\n",
    "| # | K\u00fcsimus |\n",
    "|---|--------|\n",
    "| 1 | Kas ma usun, et saan muutuda \u2014 ka selles valdkonnas, kus praegu n\u00f5rk? |\n",
    "| 2 | Kas ma otsin \u00f5ppimist, mitte ainult tulemust? |\n",
    "| 3 | Kas ma l\u00f5ikasin t\u00e4na \u00fche m\u00fcraallika (ekraan, v\u00f5rdlus)? |\n",
    "| 4 | Kas ma tegin \u00fche konkreetse teo oma WHY suunas? |\n",
    "| 5 | Kas ma kohtlesin kedagi nagu **terve inimene** (Lisa P)? |\n\n",
    "---\n\n",
    "## 8. Allikaviide\n\n",
    "- Buffalmano, L. (2018). *Ultimate Power*. The Power Moves.\n",
    "- Tugiteosed viidatud tekstis: Dweck (*Mindset*), Duckworth (*Grit*), Sinek (*Start With WHY*), Taleb (*Antifragile*), Brown (*Daring Greatly*), Manson (*Subtle Art*)\n",
    "- Repo: kasutaja \u00fcleslaaditud PDF (2026-07-24)\n\n",
    "---\n\n",
    "*Lisa AO \u2014 Operatsioon \u201ePeegel\u201c. Ultimate Power kokkuv\u00f5te demomehe t\u00f6\u00f6riistakastis. Viimati uuendatud: 2026-07-24.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
