#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate Lisa AQ - sidepakkide jaotus skeem."""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "lisad" / "lisa-aq-sidepakkide-jaotus-skeem.md"

parts = [
    "# Lisa AQ \u2014 Sidepakkide jaotus skeem\n\n",
    "**Eesm\u00e4rk:** Kellele mis pakett, mis kanal, mis saatja \u2014 ilma \u00fclekoormata.  \n",
    "**Seotud:** Lisa AP (lugejateed), Lisa AJ (levitamine), Lisa AN (RU), Lisa N (demomehed)  \n",
    "**Kuup\u00e4ev:** 24. juuli 2026\n\n",
    "> **Lugeja saab:** \u00fche selge skeemi \u2014 kuidas materjal inimeseni j\u00f5uab.  \n",
    "> **Loe seda kui:** saadad, koordineerid v\u00f5i valmistad tr\u00fcki.  \n",
    "> **\u00c4ra loe kui:** oled lihtsalt lugeja \u2014 alusta **PEEGEL_TUUM.pdf**-st.\n\n",
    "---\n\n",
    "## 1. Kihtide arhitektuur (K0\u2013K3)\n\n",
    "| Kiht | Nimi | Maht | Kellele | Fail |\n",
    "|------|------|------|---------|------|\n",
    "| **K0** | **TUUM** | ~30 lk | Esimene kontakt, iga\u00fcks | `PEEGEL_TUUM.pdf` |\n",
    "| **K1** | **TEED** (A\u2013F) | ~50\u201380 lk/tee | Vali \u00fcks tee oma olukorra jaoks | `PEEGEL_TEE_A.pdf` \u2026 `PEEGEL_TEE_F.pdf` |\n",
    "| **K2** | **RAAMATUKOGU** | T\u00e4ielik | Soovija, kes tahab k\u00f5ike | `OPERATSIOON_PEEGEL_OPORD.pdf` |\n",
    "| **K3** | **SPETSIALIST** | N\u00f5udmisel | Juht, anal\u00fc\u00fctik, partner | Lisa T, AL, AA, AF, AC, Y |\n\n",
    "**Reegel:** Vaikimisi anna ainult **K0**. Edasi ainult kui inimene k\u00fcsib v\u00f5i tee on selge.\n\n",
    "---\n\n",
    "## 2. Sidepakkide jaotus \u2014 \u00fclevaade\n\n",
    "```mermaid\n",
    "flowchart TD\n",
    "    R[Renee / koordinaator] --> DM[Demomees SOK]\n",
    "    R --> HL[Heli Steiger]\n",
    "    R --> MU[Mihhail U\u0161akov RU]\n",
    "    DM --> P0[P0-TUUM]\n",
    "    P0 --> TEE{Vali tee A-F}\n",
    "    TEE --> PA[P1-A Kriis]\n",
    "    TEE --> PB[P1-B Skeptik]\n",
    "    TEE --> PC[P1-C Pere]\n",
    "    TEE --> PD[P1-D Demomees]\n",
    "    TEE --> PE[P1-E RU]\n",
    "    TEE --> PF[P1-F Juht]\n",
    "    PA --> P2[P2-TAIS kui k\u00fcsib]\n",
    "    PB --> P2\n",
    "    PC --> P2\n",
    "    PD --> P2\n",
    "    PE --> P2\n",
    "    PF --> P3[P3-SPETSIALIST]\n",
    "    HL --> PH[P-HELI oigused]\n",
    "    MU --> PE\n",
    "```\n\n",
    "---\n\n",
    "## 3. Sidepakkide tabel\n\n",
    "| Pakett | Kiht | Kellele | Saatja | Kanal | Sisaldab |\n",
    "|--------|------|---------|--------|-------|----------|\n",
    "| **P0-TUUM** | K0 | Esimene kontakt | Demomees | K\u00e4est-k\u00e4tte, QR, lendleht | `PEEGEL_TUUM.pdf` + taskukaart |\n",
    "| **P1-A-KRIIS** | K1 | Isa kriisis | Usaldusisik / demomees | Privaatne, 1:1 | `PEEGEL_TEE_A.pdf` + LOO taskukaardid |\n",
    "| **P1-B-SKEPTIK** | K1 | Ei usu kohe | Demomees | Vestlus \u2192 link | `PEEGEL_TEE_B.pdf` |\n",
    "| **P1-C-PERE** | K1 | Pere tugevdamine | Demomees / kool | Kohtumine, WhatsApp | `PEEGEL_TEE_C.pdf` |\n",
    "| **P1-D-DEMO** | K1 | SOK demomees | Renee / \u00fcksuse juht | Aluste_kool | `PEEGEL_TEE_D.pdf` + Lisa AO |\n",
    "| **P1-E-RU** | K1 | Venekeelne kodanik | M. U\u0161akov (kandidaat) | RU kanal eraldi | `PEEGEL_RU_KIHT0.pdf` + Lisa AN |\n",
    "| **P1-F-JUHT** | K1 | KV, koolijuht | Renee | Ametlik e-kiri | `PEEGEL_TEE_F.pdf` |\n",
    "| **P2-TAIS** | K2 | Soovija \u201ek\u00f5ik\u201c | Demomees + AJ kinnitus | Kontrollitud link | `OPERATSIOON_PEEGEL_OPORD.pdf` |\n",
    "| **P3-SPETS** | K3 | Anal\u00fc\u00fctik, partner | Renee n\u00f5udmisel | 1:1 | Lisa T, AL, AA, AF, AC, Y |\n",
    "| **P-HELI** | \u2014 | Steiger / Huber | Renee | E-kiri | Lisa AM + I + vastus Helile |\n",
    "| **P-OPSEC** | \u2014 | Sisering | Renee | Kr\u00fcpteeritud | Lisa K, AJ, AL (mitte avalik) |\n\n",
    "---\n\n",
    "## 4. Teede sisud (K1)\n\n",
    "| Tee | PDF | Failid |\n",
    "|-----|-----|--------|\n",
    "| **A** Kriis | `PEEGEL_TEE_A.pdf` | Lisa H \u2192 raamat F \u2192 Lisa P \u2192 Lisa AD |\n",
    "| **B** Skeptik | `PEEGEL_TEE_B.pdf` | TUUM tuum \u2192 Lisa R \u2192 Lisa T (kokkuv\u00f5te) |\n",
    "| **C** Pere | `PEEGEL_TEE_C.pdf` | raamat A \u2192 D \u2192 E \u2192 Lisa M |\n",
    "| **D** Demomees | `PEEGEL_TEE_D.pdf` | Lisa N \u2192 I \u2192 Q \u2192 AO \u2192 Lisa X |\n",
    "| **E** RU | `PEEGEL_RU_KIHT0.pdf` | kiht0-ru \u2192 Lisa AN |\n",
    "| **F** Juht | `PEEGEL_TEE_F.pdf` | Lisa I \u2192 P \u2192 L |\n\n",
    "---\n\n",
    "## 5. Levitamise reeglid\n\n",
    "| Reegel | P\u00f5hjus |\n",
    "|--------|--------|\n",
    "1. **Alusta K0-st** | Maht/fookus \u2014 \u00fclekoormus tapab usalduse (Lisa AP) |\n",
    "2. **\u00dcks tee korraga** | Lugeja valib A\u2013F, mitte \u201ek\u00f5ik\u201c |\n",
    "3. **RU eraldi kanal** | Heli ei kirjasta RU raamatuid (Lisa AN) |\n",
    "4. **K2 ainult k\u00fcsimisel** | Lisa AJ lugemiskinnitus |\n",
    "5. **K3 ainult vajadusel** | T, AL sisemised \u2014 mitte mass |\n",
    "6. **Taskukaart alati kaasas** | Pocketsize igap\u00e4ev (Lisa X) |\n",
    "7. **Trauma enne loogikat** | Lisa P enne debatti |\n\n",
    "---\n\n",
    "## 6. ZIP-struktuur (`Operatsioon-Peegel-sidepakkid.zip`)\n\n",
    "```\n",
    "sidepakkid/\n",
    "  P0-TUUM/\n",
    "    PEEGEL_TUUM.pdf\n",
    "    TASKUKAARDID_RAHAKOTT.pdf\n",
    "    README.txt\n",
    "  P1-TEE-A-KRIIS/\n",
    "    PEEGEL_TEE_A.pdf\n",
    "    LOO_TASKUKAARDID_RAHAKOTT.pdf\n",
    "  P1-TEE-B-SKEPTIK/\n",
    "    PEEGEL_TEE_B.pdf\n",
    "  P1-TEE-C-PERE/\n",
    "    PEEGEL_TEE_C.pdf\n",
    "  P1-TEE-D-DEMO/\n",
    "    PEEGEL_TEE_D.pdf\n",
    "  P1-TEE-E-RU/\n",
    "    PEEGEL_RU_KIHT0.pdf\n",
    "  P1-TEE-F-JUHT/\n",
    "    PEEGEL_TEE_F.pdf\n",
    "  P2-TAIS/\n",
    "    OPERATSIOON_PEEGEL_OPORD.pdf\n",
    "  P3-SPETSIALIST/\n",
    "    README-spetsialist.txt\n",
    "```\n\n",
    "Genereerimine: `python3 generate_packages.py`\n\n",
    "---\n\n",
    "## 7. Kanalite maatriks\n\n",
    "| Kanal | Paketid | OPSEC |\n",
    "|-------|---------|-------|\n",
    "| K\u00e4est-k\u00e4tte + lendleht | P0 | Madal |\n",
    "| WhatsApp / Signal 1:1 | P1-A, P1-C | Keskmine |\n",
    "| Aluste_kool koosolek | P1-D | Madal |\n",
    "| RU kogukond (Mihhail) | P1-E | Keskmine |\n",
    "| Ametlik e-kiri | P1-F, P-HELI | K\u00f5rge |\n",
    "| GitHub / ZIP link | P2 | Lisa AJ kinnitus |\n",
    "| Sisering | P3, P-OPSEC | K\u00f5rge |\n\n",
    "---\n\n",
    "## 8. M\u00f5istmise signaal (inimlik, mitte operatiivne)\n\n",
    "See operatsioon s\u00fcndis t\u00f6\u00f6st. Aga selle taga on ka inimene.\n\n",
    "Kui sa loed seda materjali ja **m\u00e4rgad** midagi inimlikku \u2014 mitte plaanina, vaid inimesena \u2014",
    "v\u00f5id saata \u00fche lause:\n\n",
    "> **\u201eJah ma m\u00f5istan sind Renee\U0001f917\u201c**  \n",
    "> SMS: **56980062**\n\n",
    "See ei ole k\u00fcsimus ega kutse liituda. See on lihtsalt m\u00e4rk, et keegi **n\u00e4gi**.\n\n",
    "---\n\n",
    "## 9. J\u00e4rgmised sammud\n\n",
    "| # | Tegevus | Vastutaja | Staatus |\n",
    "|---|---------|-----------|--------|\n",
    "| 1 | Genereeri sidepakkide ZIP | Skript | Valmis |\n",
    "| 2 | 100 demomehe pilot P0 | Renee | Lisa N |\n",
    "| 3 | Mihhail kinnitus P1-E | Renee | Ootel |\n",
    "| 4 | Heli vastus P-HELI | Renee | Ootel |\n",
    "| 5 | Tagasiside p\u00e4rast 30 p\u00e4eva | Demomehed | Lisa AP audit |\n\n",
    "---\n\n",
    "*Lisa AQ \u2014 Operatsioon \u201ePeegel\u201c. Sidepakkide jaotus skeem. 2026-07-24.*\n",
]

OUT.write_text("".join(parts), encoding="utf-8")
print(f"Wrote {OUT}")
